import type { Person, Restaurant } from "./types";
import { CITIES } from "./cities";

function city(name: string) {
  const c = CITIES.find((c) => c.name === name);
  if (!c) throw new Error(`Unknown city: ${name}`);
  return c;
}

export const IDEA_TAGS = [
  "AI / Machine Learning",
  "E-commerce",
  "Food & Restaurants",
  "Fintech",
  "Real Estate",
  "Health & Fitness",
  "Fashion",
  "Trucking & Logistics",
  "Content Creation",
  "Education",
  "Travel",
  "Gaming",
  "Crypto / Web3",
  "Marketing Agency",
  "SaaS",
  "Import / Export",
  "Beauty & Barbering",
  "Music",
  "Sports",
  "Green Energy",
];

export const PEOPLE: Person[] = [
  {
    id: "p1",
    name: "Marcus Reid",
    jobTitle: "Software Engineer",
    ideaTags: ["AI / Machine Learning", "SaaS"],
    bio: "Building AI tools on nights and weekends. Looking for a co-founder who thinks big.",
    city: city("New York"),
    travel: "worldwide",
    emoji: "🧑🏾‍💻",
  },
  {
    id: "p2",
    name: "Sofia Alvarez",
    jobTitle: "Restaurant Owner",
    ideaTags: ["Food & Restaurants", "E-commerce"],
    bio: "Own two taquerias, want to franchise. Happy to host meetups at my spot.",
    city: city("Mexico City"),
    travel: "worldwide",
    emoji: "👩🏽‍🍳",
  },
  {
    id: "p3",
    name: "Dele Okafor",
    jobTitle: "Logistics Manager",
    ideaTags: ["Trucking & Logistics", "Import / Export"],
    bio: "10 years moving freight. Building a dispatch platform for owner-operators.",
    city: city("Lagos"),
    travel: "worldwide",
    emoji: "👨🏿‍💼",
  },
  {
    id: "p4",
    name: "Emma Chen",
    jobTitle: "Product Designer",
    ideaTags: ["SaaS", "Health & Fitness"],
    bio: "Designer turned founder. Prototyping a wellness app, need technical partners.",
    city: city("Singapore"),
    travel: "country",
    emoji: "👩🏻‍🎨",
  },
  {
    id: "p5",
    name: "James Carter",
    jobTitle: "Truck Driver",
    ideaTags: ["Trucking & Logistics", "Real Estate"],
    bio: "Owner-operator saving to buy my first fleet. Real estate on the side.",
    city: city("Atlanta"),
    travel: "country",
    emoji: "🧔🏾",
  },
  {
    id: "p6",
    name: "Léa Dubois",
    jobTitle: "Marketing Consultant",
    ideaTags: ["Marketing Agency", "Fashion"],
    bio: "Ex-agency lead. Starting a boutique agency for fashion brands.",
    city: city("Paris"),
    travel: "worldwide",
    emoji: "👩🏼‍💼",
  },
  {
    id: "p7",
    name: "Raj Patel",
    jobTitle: "Financial Analyst",
    ideaTags: ["Fintech", "Crypto / Web3"],
    bio: "Numbers guy with a payments startup idea. Weekend chess player.",
    city: city("Mumbai"),
    travel: "worldwide",
    emoji: "👨🏽‍💼",
  },
  {
    id: "p8",
    name: "Aisha Mohammed",
    jobTitle: "Nurse",
    ideaTags: ["Health & Fitness", "Education"],
    bio: "RN building a training platform for new nurses. Passionate about mentorship.",
    city: city("Dubai"),
    travel: "country",
    emoji: "👩🏾‍⚕️",
  },
  {
    id: "p9",
    name: "Tom Nguyen",
    jobTitle: "Chef",
    ideaTags: ["Food & Restaurants", "Content Creation"],
    bio: "Head chef, food content on the side. Dream: a fusion spot with a story.",
    city: city("Sydney"),
    travel: "worldwide",
    emoji: "👨🏻‍🍳",
  },
  {
    id: "p10",
    name: "Grace Kim",
    jobTitle: "Software Engineer",
    ideaTags: ["Gaming", "AI / Machine Learning"],
    bio: "Game dev by day. Building an indie studio, one jam at a time.",
    city: city("Seoul"),
    travel: "country",
    emoji: "👩🏻‍💻",
  },
  {
    id: "p11",
    name: "Carlos Mendes",
    jobTitle: "Real Estate Agent",
    ideaTags: ["Real Estate", "Fintech"],
    bio: "Top agent in my region. Want to build proptech for emerging markets.",
    city: city("São Paulo"),
    travel: "worldwide",
    emoji: "🧑🏽‍💼",
  },
  {
    id: "p12",
    name: "Nina Petrova",
    jobTitle: "Barber & Shop Owner",
    ideaTags: ["Beauty & Barbering", "E-commerce"],
    bio: "Own a barbershop, launching my own product line. Love talking shop.",
    city: city("Berlin"),
    travel: "country",
    emoji: "💇🏼‍♀️",
  },
  {
    id: "p13",
    name: "David Osei",
    jobTitle: "Teacher",
    ideaTags: ["Education", "Content Creation"],
    bio: "High school teacher creating online courses. Education should travel.",
    city: city("London"),
    travel: "worldwide",
    emoji: "👨🏿‍🏫",
  },
  {
    id: "p14",
    name: "Yuki Tanaka",
    jobTitle: "Travel Blogger",
    ideaTags: ["Travel", "Content Creation"],
    bio: "60 countries and counting. Building a travel-planning app for foodies.",
    city: city("Tokyo"),
    travel: "worldwide",
    emoji: "🧳",
  },
  {
    id: "p15",
    name: "Mike Johnson",
    jobTitle: "Personal Trainer",
    ideaTags: ["Health & Fitness", "Sports"],
    bio: "Trainer with a gym-franchise dream. Meet me over a protein-heavy lunch.",
    city: city("Chicago"),
    travel: "country",
    emoji: "🏋🏾‍♂️",
  },
  {
    id: "p16",
    name: "Fatima Hassan",
    jobTitle: "Fashion Designer",
    ideaTags: ["Fashion", "E-commerce"],
    bio: "Modest-fashion line in the works. Looking for supply-chain minds.",
    city: city("Nairobi"),
    travel: "worldwide",
    emoji: "👗",
  },
  {
    id: "p17",
    name: "Liam O'Brien",
    jobTitle: "Musician",
    ideaTags: ["Music", "Content Creation"],
    bio: "Producer building a platform for independent artists to tour smart.",
    city: city("Toronto"),
    travel: "worldwide",
    emoji: "🎸",
  },
  {
    id: "p18",
    name: "Ana Rodríguez",
    jobTitle: "Solar Engineer",
    ideaTags: ["Green Energy", "SaaS"],
    bio: "Engineer with a plan for affordable community solar. Coffee or asado?",
    city: city("Buenos Aires"),
    travel: "worldwide",
    emoji: "👩🏽‍🔧",
  },
];

export const RESTAURANTS: Restaurant[] = [
  { id: "r1", name: "The Corner Table", cuisine: "American", city: "New York", country: "USA", lat: 40.72, lng: -74.0, priceLevel: 2, vibe: "Cozy booths, good for long talks" },
  { id: "r2", name: "Habibi Grill", cuisine: "Middle Eastern", city: "New York", country: "USA", lat: 40.75, lng: -73.99, priceLevel: 1, vibe: "Casual, generous plates" },
  { id: "r3", name: "Sunset & Vine", cuisine: "Californian", city: "Los Angeles", country: "USA", lat: 34.09, lng: -118.33, priceLevel: 3, vibe: "Patio seating, deal-closing energy" },
  { id: "r4", name: "Deep Dish Society", cuisine: "Pizza", city: "Chicago", country: "USA", lat: 41.89, lng: -87.63, priceLevel: 2, vibe: "Loud, fun, shareable" },
  { id: "r5", name: "Cafecito 305", cuisine: "Cuban", city: "Miami", country: "USA", lat: 25.76, lng: -80.19, priceLevel: 1, vibe: "Fast coffee, faster ideas" },
  { id: "r6", name: "Smoke & Oak", cuisine: "BBQ", city: "Houston", country: "USA", lat: 29.76, lng: -95.37, priceLevel: 2, vibe: "Brisket and business" },
  { id: "r7", name: "Peach Street Diner", cuisine: "Southern", city: "Atlanta", country: "USA", lat: 33.75, lng: -84.39, priceLevel: 1, vibe: "Comfort food, no rush" },
  { id: "r8", name: "Maple & King", cuisine: "Canadian", city: "Toronto", country: "Canada", lat: 43.65, lng: -79.38, priceLevel: 2, vibe: "Bright, modern, quiet corners" },
  { id: "r9", name: "La Casa Azul", cuisine: "Mexican", city: "Mexico City", country: "Mexico", lat: 19.43, lng: -99.13, priceLevel: 2, vibe: "Courtyard tables, great mole" },
  { id: "r10", name: "The Gilded Fork", cuisine: "British", city: "London", country: "UK", lat: 51.51, lng: -0.13, priceLevel: 3, vibe: "Classic, impress-a-partner spot" },
  { id: "r11", name: "Chez Lumière", cuisine: "French", city: "Paris", country: "France", lat: 48.86, lng: 2.35, priceLevel: 3, vibe: "Candlelit, unhurried" },
  { id: "r12", name: "Currywurst Haus", cuisine: "German", city: "Berlin", country: "Germany", lat: 52.52, lng: 13.4, priceLevel: 1, vibe: "Standing tables, quick sync" },
  { id: "r13", name: "El Mercado", cuisine: "Spanish", city: "Madrid", country: "Spain", lat: 40.42, lng: -3.7, priceLevel: 2, vibe: "Tapas built for sharing ideas" },
  { id: "r14", name: "Mama Nkechi's", cuisine: "Nigerian", city: "Lagos", country: "Nigeria", lat: 6.52, lng: 3.38, priceLevel: 1, vibe: "Jollof that seals partnerships" },
  { id: "r15", name: "Savanna Table", cuisine: "Kenyan", city: "Nairobi", country: "Kenya", lat: -1.29, lng: 36.82, priceLevel: 2, vibe: "Garden setting, calm" },
  { id: "r16", name: "Al Safina", cuisine: "Emirati", city: "Dubai", country: "UAE", lat: 25.2, lng: 55.27, priceLevel: 3, vibe: "Marina views, big-vision talks" },
  { id: "r17", name: "Masala House", cuisine: "Indian", city: "Mumbai", country: "India", lat: 19.08, lng: 72.88, priceLevel: 1, vibe: "Buzzing, endless chai refills" },
  { id: "r18", name: "Hawker 88", cuisine: "Singaporean", city: "Singapore", country: "Singapore", lat: 1.35, lng: 103.82, priceLevel: 1, vibe: "Hawker classics, zero pretension" },
  { id: "r19", name: "Sakura Ichiban", cuisine: "Japanese", city: "Tokyo", country: "Japan", lat: 35.68, lng: 139.65, priceLevel: 2, vibe: "Counter seats, focused energy" },
  { id: "r20", name: "Seoul Ember", cuisine: "Korean BBQ", city: "Seoul", country: "South Korea", lat: 37.57, lng: 126.98, priceLevel: 2, vibe: "Grill-side bonding" },
  { id: "r21", name: "Harbour Fire", cuisine: "Australian", city: "Sydney", country: "Australia", lat: -33.87, lng: 151.21, priceLevel: 3, vibe: "Waterfront, celebratory" },
  { id: "r22", name: "Fogo do Bairro", cuisine: "Brazilian", city: "São Paulo", country: "Brazil", lat: -23.55, lng: -46.63, priceLevel: 2, vibe: "Churrasco, long lunches" },
  { id: "r23", name: "Parrilla del Sur", cuisine: "Argentine", city: "Buenos Aires", country: "Argentina", lat: -34.6, lng: -58.38, priceLevel: 2, vibe: "Steak and strategy" },
];
