import type { Person } from "./types";
import { CITIES } from "./cities";

/**
 * Sample members for local demos only. Never loaded unless
 * NEXT_PUBLIC_ENABLE_DEMO_PROFILES=1, so the live room stays real people.
 */
function city(name: string) {
  const c = CITIES.find((c) => c.name === name);
  if (!c) throw new Error(`Unknown city: ${name}`);
  return c;
}

export const DEMO_PEOPLE: Person[] = [
  {
    id: "p1",
    name: "Marcus Reid",
    jobTitle: "Software Engineer",
    ideaTags: ["AI / Machine Learning", "SaaS"],
    lookingFor: ["Co-founder", "Partnership"],
    bio: "Building AI tools on nights and weekends. Looking for a co-founder who thinks big.",
    city: city("New York"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/men/32.jpg",
    verifications: ["linkedin"],
    linkedInUrl: "https://www.linkedin.com/in/marcus-reid",
    websiteUrl: "https://briefly.ai",
    portfolioUrl: "https://github.com/marcusreid",
    work: [
      {
        title: "Briefly AI",
        kind: "app",
        description: "iOS app that turns meeting notes into action items with GPT.",
        url: "https://apps.apple.com",
      },
      {
        title: "Briefly (web)",
        kind: "website",
        description: "Landing + waitlist for the AI note-taker.",
        url: "https://briefly.ai",
      },
      {
        title: "Open-source NLP utils",
        kind: "portfolio",
        description: "TypeScript helpers for summarization pipelines.",
        url: "https://github.com/marcusreid",
      },
    ],
  },
  {
    id: "p2",
    blackConnections: 2,
    name: "Sofia Alvarez",
    jobTitle: "Restaurant Owner",
    ideaTags: ["Food & Restaurants", "E-commerce"],
    lookingFor: ["Partnership", "Clients"],
    bio: "Own two taquerias, want to franchise. Happy to host meetups at my spot.",
    city: city("Mexico City"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/women/44.jpg",
    verifications: ["company-email"],
    linkedInUrl: "https://www.linkedin.com/in/sofia-alvarez",
    websiteUrl: "https://tacossoul.mx",
    work: [
      {
        title: "Tacos Soul Condesa",
        kind: "company",
        description: "Flagship taqueria — 40 seats, late-night line around the block.",
        url: "https://tacossoul.mx",
      },
      {
        title: "Tacos Soul Roma Norte",
        kind: "company",
        description: "Second location focused on catering & private dinners.",
      },
      {
        title: "Soul Salsa (D2C)",
        kind: "product",
        description: "Bottled house salsas shipping across Mexico.",
        url: "https://shop.tacossoul.mx",
      },
    ],
  },
  {
    id: "p3",
    name: "Dele Okafor",
    jobTitle: "Logistics Manager",
    ideaTags: ["Trucking & Logistics", "Import / Export"],
    lookingFor: ["Co-founder", "Investor"],
    bio: "10 years moving freight. Building a dispatch platform for owner-operators.",
    city: city("Lagos"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/men/75.jpg",
    verifications: ["website"],
    linkedInUrl: "https://www.linkedin.com/in/dele-okafor",
    websiteUrl: "https://hauldesk.africa",
    work: [
      {
        title: "HaulDesk",
        kind: "app",
        description: "Dispatch + load board for West African owner-operators.",
        url: "https://hauldesk.africa",
      },
      {
        title: "HaulDesk Ops",
        kind: "website",
        description: "Fleet dashboard for brokers and warehouse partners.",
        url: "https://ops.hauldesk.africa",
      },
    ],
  },
  {
    id: "p4",
    name: "Emma Chen",
    jobTitle: "Product Designer",
    ideaTags: ["SaaS", "Health & Fitness"],
    lookingFor: ["Co-founder", "Hiring"],
    bio: "Designer turned founder. Prototyping a wellness app, need technical partners.",
    city: city("Singapore"),
    travel: "country",
    photoUrl: "https://randomuser.me/api/portraits/women/65.jpg",
    verifications: ["portfolio"],
    linkedInUrl: "https://www.linkedin.com/in/emma-chen-design",
    portfolioUrl: "https://emmachen.design",
    websiteUrl: "https://pulsewell.app",
    work: [
      {
        title: "PulseWell",
        kind: "app",
        description: "Habit + recovery tracker with coach check-ins. Beta on TestFlight.",
        url: "https://pulsewell.app",
      },
      {
        title: "Design portfolio",
        kind: "portfolio",
        description: "Case studies from fintech and health products.",
        url: "https://emmachen.design",
      },
    ],
  },
  {
    id: "p5",
    name: "James Carter",
    jobTitle: "Truck Driver",
    ideaTags: ["Trucking & Logistics", "Real Estate"],
    lookingFor: ["Investor", "Networking"],
    bio: "Owner-operator saving to buy my first fleet. Real estate on the side.",
    city: city("Atlanta"),
    travel: "country",
    photoUrl: "https://randomuser.me/api/portraits/men/22.jpg",
    verifications: ["registration"],
    linkedInUrl: "https://www.linkedin.com/in/james-carter-trucking",
    websiteUrl: "https://carterhauls.com",
    work: [
      {
        title: "Carter Hauls LLC",
        kind: "company",
        description: "Owner-operator OTR — dry van, Southeast ↔ Midwest.",
        url: "https://carterhauls.com",
      },
      {
        title: "Duplex flip · East Atlanta",
        kind: "project",
        description: "First rental property under renovation.",
      },
    ],
  },
  {
    id: "p6",
    blackConnections: 5,
    name: "Léa Dubois",
    jobTitle: "Marketing Consultant",
    ideaTags: ["Marketing Agency", "Fashion"],
    lookingFor: ["Clients", "Partnership"],
    bio: "Ex-agency lead. Starting a boutique agency for fashion brands.",
    city: city("Paris"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/women/12.jpg",
    verifications: ["linkedin"],
    linkedInUrl: "https://www.linkedin.com/in/lea-dubois",
    websiteUrl: "https://atelierlea.co",
    work: [
      {
        title: "Atelier Léa",
        kind: "company",
        description: "Boutique growth studio for fashion & lifestyle brands.",
        url: "https://atelierlea.co",
      },
      {
        title: "Campaign work",
        kind: "portfolio",
        description: "Selected launches for Paris and Milan labels.",
        url: "https://atelierlea.co/work",
      },
    ],
  },
  {
    id: "p7",
    name: "Raj Patel",
    jobTitle: "Financial Analyst",
    ideaTags: ["Fintech", "Crypto / Web3"],
    lookingFor: ["Investor", "Co-founder"],
    bio: "Numbers guy with a payments startup idea. Weekend chess player.",
    city: city("Mumbai"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/men/45.jpg",
    verifications: ["company-email"],
    linkedInUrl: "https://www.linkedin.com/in/raj-patel-fin",
    websiteUrl: "https://clearsettle.io",
    work: [
      {
        title: "ClearSettle",
        kind: "product",
        description: "B2B payout rails for cross-border freelancers (prototype).",
        url: "https://clearsettle.io",
      },
      {
        title: "Market notes",
        kind: "content",
        description: "Weekly fintech + crypto briefings for founders.",
        url: "https://clearsettle.io/notes",
      },
    ],
  },
  {
    id: "p8",
    name: "Aisha Mohammed",
    jobTitle: "Nurse",
    ideaTags: ["Health & Fitness", "Education"],
    lookingFor: ["Mentor", "Partnership"],
    bio: "RN building a training platform for new nurses. Passionate about mentorship.",
    city: city("Dubai"),
    travel: "country",
    photoUrl: "https://randomuser.me/api/portraits/women/89.jpg",
    verifications: ["website"],
    linkedInUrl: "https://www.linkedin.com/in/aisha-mohammed-rn",
    websiteUrl: "https://nurseladder.com",
    work: [
      {
        title: "NurseLadder",
        kind: "website",
        description: "Online clinical skills modules for new RNs in the Gulf.",
        url: "https://nurseladder.com",
      },
      {
        title: "NurseLadder Learn",
        kind: "app",
        description: "Mobile drills + mentor matching (Android beta).",
        url: "https://nurseladder.com/app",
      },
    ],
  },
  {
    id: "p9",
    name: "Tom Nguyen",
    jobTitle: "Chef",
    ideaTags: ["Food & Restaurants", "Content Creation"],
    lookingFor: ["Clients", "Investor"],
    bio: "Head chef, food content on the side. Dream: a fusion spot with a story.",
    city: city("Sydney"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/men/64.jpg",
    verifications: ["portfolio"],
    linkedInUrl: "https://www.linkedin.com/in/tom-nguyen-chef",
    portfolioUrl: "https://tomnguyen.kitchen",
    websiteUrl: "https://tomnguyen.kitchen",
    work: [
      {
        title: "Kitchen stories",
        kind: "content",
        description: "YouTube + Instagram series on Viet-Aussie fusion.",
        url: "https://tomnguyen.kitchen",
      },
      {
        title: "Private dining pop-ups",
        kind: "company",
        description: "Monthly 12-seat dinners in Surry Hills.",
      },
    ],
  },
  {
    id: "p10",
    name: "Grace Kim",
    jobTitle: "Software Engineer",
    ideaTags: ["Gaming", "AI / Machine Learning"],
    lookingFor: ["Co-founder", "Hiring"],
    bio: "Game dev by day. Building an indie studio, one jam at a time.",
    city: city("Seoul"),
    travel: "country",
    photoUrl: "https://randomuser.me/api/portraits/women/33.jpg",
    verifications: ["registration"],
    linkedInUrl: "https://www.linkedin.com/in/grace-kim-dev",
    websiteUrl: "https://lanternbyte.games",
    portfolioUrl: "https://github.com/gracekim",
    work: [
      {
        title: "Lantern Byte Studio",
        kind: "company",
        description: "Indie game studio — narrative RPGs with ML NPCs.",
        url: "https://lanternbyte.games",
      },
      {
        title: "Night Ferry",
        kind: "app",
        description: "Steam early-access puzzle adventure.",
        url: "https://store.steampowered.com",
      },
    ],
  },
  {
    id: "p11",
    black: true,
    name: "Carlos Mendes",
    jobTitle: "Real Estate Agent",
    ideaTags: ["Real Estate", "Fintech"],
    lookingFor: ["Partnership", "Clients"],
    bio: "Top agent in my region. Want to build proptech for emerging markets.",
    city: city("São Paulo"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/men/18.jpg",
    verifications: ["linkedin"],
    linkedInUrl: "https://www.linkedin.com/in/carlos-mendes-re",
    websiteUrl: "https://mendesimoveis.com.br",
    work: [
      {
        title: "Mendes Imóveis",
        kind: "company",
        description: "Residential brokerage across Jardins & Pinheiros.",
        url: "https://mendesimoveis.com.br",
      },
      {
        title: "Lotify (prototype)",
        kind: "product",
        description: "Proptech tool for escrow transparency in LATAM.",
        url: "https://lotify.app",
      },
    ],
  },
  {
    id: "p12",
    name: "Nina Petrova",
    jobTitle: "Barber & Shop Owner",
    ideaTags: ["Beauty & Barbering", "E-commerce"],
    lookingFor: ["Clients", "Networking"],
    bio: "Own a barbershop, launching my own product line. Love talking shop.",
    city: city("Berlin"),
    travel: "country",
    photoUrl: "https://randomuser.me/api/portraits/women/26.jpg",
    verifications: ["company-email"],
    linkedInUrl: "https://www.linkedin.com/in/nina-petrova",
    websiteUrl: "https://steelcut.berlin",
    work: [
      {
        title: "Steel Cut Barbers",
        kind: "company",
        description: "Appointment-only shop in Kreuzberg.",
        url: "https://steelcut.berlin",
      },
      {
        title: "Steel Cut Care",
        kind: "product",
        description: "Beard oil + pomade line launching D2C.",
        url: "https://shop.steelcut.berlin",
      },
    ],
  },
  {
    id: "p13",
    name: "David Osei",
    jobTitle: "Teacher",
    ideaTags: ["Education", "Content Creation"],
    lookingFor: ["Mentor", "Clients"],
    bio: "High school teacher creating online courses. Education should travel.",
    city: city("London"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/men/86.jpg",
    verifications: ["website"],
    linkedInUrl: "https://www.linkedin.com/in/david-osei",
    websiteUrl: "https://learnwithosei.com",
    work: [
      {
        title: "Learn with Osei",
        kind: "website",
        description: "A-level maths courses for first-gen students.",
        url: "https://learnwithosei.com",
      },
      {
        title: "Classroom shorts",
        kind: "content",
        description: "TikTok / YouTube explainers with 2M+ views.",
      },
    ],
  },
  {
    id: "p14",
    name: "Yuki Tanaka",
    jobTitle: "Travel Blogger",
    ideaTags: ["Travel", "Content Creation"],
    lookingFor: ["Partnership", "Networking"],
    bio: "60 countries and counting. Building a travel-planning app for foodies.",
    city: city("Tokyo"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/women/50.jpg",
    verifications: ["portfolio"],
    linkedInUrl: "https://www.linkedin.com/in/yuki-tanaka-travel",
    websiteUrl: "https://tasteatlas.app",
    portfolioUrl: "https://yukitanaka.travel",
    work: [
      {
        title: "Taste Atlas",
        kind: "app",
        description: "Foodie itinerary planner with local chef tips.",
        url: "https://tasteatlas.app",
      },
      {
        title: "Travel journal",
        kind: "content",
        description: "Long-form city guides and dining maps.",
        url: "https://yukitanaka.travel",
      },
    ],
  },
  {
    id: "p15",
    name: "Mike Johnson",
    jobTitle: "Personal Trainer",
    ideaTags: ["Health & Fitness", "Sports"],
    lookingFor: ["Clients", "Partnership"],
    bio: "Trainer with a gym-franchise dream. Meet me over a protein-heavy lunch.",
    city: city("Chicago"),
    travel: "country",
    photoUrl: "https://randomuser.me/api/portraits/men/53.jpg",
    verifications: ["registration"],
    linkedInUrl: "https://www.linkedin.com/in/mike-johnson-pt",
    websiteUrl: "https://ironlane.fit",
    work: [
      {
        title: "Iron Lane Training",
        kind: "company",
        description: "1:1 and small-group coaching in River North.",
        url: "https://ironlane.fit",
      },
      {
        title: "Iron Lane Coach",
        kind: "app",
        description: "Programming + check-ins for remote clients.",
        url: "https://ironlane.fit/app",
      },
    ],
  },
  {
    id: "p16",
    name: "Fatima Hassan",
    jobTitle: "Fashion Designer",
    ideaTags: ["Fashion", "E-commerce"],
    lookingFor: ["Investor", "Partnership"],
    bio: "Modest-fashion line in the works. Looking for supply-chain minds.",
    city: city("Nairobi"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/women/68.jpg",
    verifications: ["linkedin"],
    linkedInUrl: "https://www.linkedin.com/in/fatima-hassan-design",
    websiteUrl: "https://hayati.studio",
    work: [
      {
        title: "Hayati Studio",
        kind: "company",
        description: "Modest ready-to-wear — Nairobi atelier + preorders.",
        url: "https://hayati.studio",
      },
      {
        title: "Hayati Shop",
        kind: "website",
        description: "E-com drop for the first capsule collection.",
        url: "https://shop.hayati.studio",
      },
    ],
  },
  {
    id: "p17",
    name: "Liam O'Brien",
    jobTitle: "Musician",
    ideaTags: ["Music", "Content Creation"],
    lookingFor: ["Investor", "Clients"],
    bio: "Producer building a platform for independent artists to tour smart.",
    city: city("Toronto"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/men/91.jpg",
    verifications: ["company-email"],
    linkedInUrl: "https://www.linkedin.com/in/liam-obrien-music",
    websiteUrl: "https://tourstack.io",
    portfolioUrl: "https://liamobrien.audio",
    work: [
      {
        title: "TourStack",
        kind: "app",
        description: "Routing + budget tool for indie tours.",
        url: "https://tourstack.io",
      },
      {
        title: "Production reel",
        kind: "portfolio",
        description: "Selected tracks and sync placements.",
        url: "https://liamobrien.audio",
      },
    ],
  },
  {
    id: "p18",
    black: true,
    name: "Ana Rodríguez",
    jobTitle: "Solar Engineer",
    ideaTags: ["Green Energy", "SaaS"],
    lookingFor: ["Investor", "Co-founder"],
    bio: "Engineer with a plan for affordable community solar. Coffee or asado?",
    city: city("Buenos Aires"),
    travel: "worldwide",
    photoUrl: "https://randomuser.me/api/portraits/women/57.jpg",
    verifications: ["website"],
    linkedInUrl: "https://www.linkedin.com/in/ana-rodriguez-solar",
    websiteUrl: "https://comunalsolar.ar",
    work: [
      {
        title: "Comunal Solar",
        kind: "company",
        description: "Community solar co-ops for apartment buildings.",
        url: "https://comunalsolar.ar",
      },
      {
        title: "Comunal Grid",
        kind: "product",
        description: "SaaS for co-op billing and generation tracking.",
        url: "https://grid.comunalsolar.ar",
      },
    ],
  },
];
